#!/bin/bash
#
# Setup (with option to run) SPM12 normalise estimate module using shell
# script invoking matlab.
#
# Usage: spm_normalise_est sourceimgfn template mbfn rf
#
# sourceimgfn - Singular source image (to have normalisation estimated).
# affreg - Affine registration template, mni | eastern | subj | none | 0 |.
# mbfn - Matlab batch output file name.
# rf - flag to run matlabbatch, 0: no, 1: yes
#
# 20220519 Created by Josh Goh.

# Assign parameters
sourceimgfn=${1}
affreg=${2}
mbfn=${3}
rf=${4}

# Call matlab with input script
unset DISPLAY
matlab -nosplash > matlab.out << EOF
  settings;
  spmpath = which('spm');
  [p n e] = fileparts(spmpath);
  matlabbatch{1,1}.spm.spatial.normalise.est.subj.vol = {'${sourceimgname},1'};
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.biasreg = 1.0000e-3;
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.biasfwhm = 60;
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.tpm = {[p '/tpm/TPM.nii']};
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.reg = [0 1.0000e-03 0.5000 0.0500 0.2000];
  if ${affreg} == 0
	affreg = '';
  else
	affreg = '${affreg}';
  end
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.affreg = affreg;
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.fwhm = 0;
  matlabbatch{1,1}.spm.spatial.normalise.est.eoptions.samp = 3;
  save('${mbfn}','matlabbatch');
  if strcmp(${rf},1),
    spm_jobman('run',matlabbatch);
  end
exit;
EOF
